import type { SNSPreset, SNSPresetKey } from '../types';

export const SNS_PRESETS: Record<SNSPresetKey, SNSPreset> = {
  'instagram-square': {
    key: 'instagram-square',
    label: 'Instagram 正方形',
    labelEn: 'Instagram Square',
    width: 1080,
    height: 1080,
    platform: 'instagram',
  },
  'instagram-portrait': {
    key: 'instagram-portrait',
    label: 'Instagram 縦長',
    labelEn: 'Instagram Portrait',
    width: 1080,
    height: 1350,
    platform: 'instagram',
  },
  'instagram-story': {
    key: 'instagram-story',
    label: 'Instagram ストーリー',
    labelEn: 'Instagram Story',
    width: 1080,
    height: 1920,
    platform: 'instagram',
  },
  'twitter-square': {
    key: 'twitter-square',
    label: 'X（Twitter）正方形',
    labelEn: 'X (Twitter) Square',
    width: 1080,
    height: 1080,
    platform: 'twitter',
  },
  'twitter-landscape': {
    key: 'twitter-landscape',
    label: 'X（Twitter）横長',
    labelEn: 'X (Twitter) Landscape',
    width: 1600,
    height: 900,
    platform: 'twitter',
  },
  'twitter-header': {
    key: 'twitter-header',
    label: 'X（Twitter）ヘッダー',
    labelEn: 'X (Twitter) Header',
    width: 1500,
    height: 500,
    platform: 'twitter',
  },
  'linkedin-post': {
    key: 'linkedin-post',
    label: 'LinkedIn 投稿',
    labelEn: 'LinkedIn Post',
    width: 1200,
    height: 627,
    platform: 'linkedin',
  },
  'linkedin-banner': {
    key: 'linkedin-banner',
    label: 'LinkedIn バナー',
    labelEn: 'LinkedIn Banner',
    width: 1584,
    height: 396,
    platform: 'linkedin',
  },
  'facebook-post': {
    key: 'facebook-post',
    label: 'Facebook 投稿',
    labelEn: 'Facebook Post',
    width: 1200,
    height: 630,
    platform: 'facebook',
  },
  'facebook-cover': {
    key: 'facebook-cover',
    label: 'Facebook カバー',
    labelEn: 'Facebook Cover',
    width: 820,
    height: 312,
    platform: 'facebook',
  },
  custom: {
    key: 'custom',
    label: 'カスタムサイズ',
    labelEn: 'Custom Size',
    width: 1080,
    height: 1080,
    platform: 'custom',
  },
};

export const PRESET_GROUPS = {
  instagram: ['instagram-square', 'instagram-portrait', 'instagram-story'],
  twitter: ['twitter-square', 'twitter-landscape', 'twitter-header'],
  linkedin: ['linkedin-post', 'linkedin-banner'],
  facebook: ['facebook-post', 'facebook-cover'],
  custom: ['custom'],
} as const;
